name: Check pull request 👀
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Upgraded to v4 for better performance
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Upgraded to v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'  # Enables Gradle caching
          
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2  # Added dedicated Gradle cache
        with:
          gradle-home-cache-cleanup: true
          
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.APP_GOOGLE_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./bitapp/google-services.json
        
      - name: Create local.properties
        env:
          FIREBASE_WEB_CLIENT_ID: ${{ secrets.FIREBASE_WEB_CLIENT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "firebaseWebClient=${FIREBASE_WEB_CLIENT_ID}" > ./local.properties
          echo "apiKey=${GEMINI_API_KEY}" >> ./local.properties
          
      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew :bitapp:assembleDebug --parallel --daemon --build-cache --configure-on-demand
